import cv2
import pathlib

# ── Side-view camera (Android IP stream) ─────────────────────────────
SIDE_CAMERA_ID = "#"
SIDE_CAMERA_MATRIX_PATH = "calibration_files/side_view/camera_matrix.npy"
SIDE_DIST_COEFFS_PATH = "calibration_files/side_view/dist_coeffs.npy"

# ── Wrist camera (USB) ────────────────────────────────────────────────
WRIST_CAMERA_ID = 0  # change if USB index differs
WRIST_CAMERA_MATRIX_PATH = "calibration_files/wrist/camera_matrix.npy"
WRIST_DIST_COEFFS_PATH = "calibration_files/wrist/dist_coeffs.npy"
WRIST_HANDEYE_PATH = "calibration_files/wrist/T_cam2gripper.npy"

# ── SO-101 follower arm — hand-eye calibration ────────────────────────
# Serial port of the follower arm USB adapter.
# FOLLOWER_PORT = "/dev/ttyACM0"
FOLLOWER_PORT = "your_follower_port_id"

# Lerobot calibration JSON for the follower arm.
# Generated by: lerobot-calibrate --robot.type=so101_follower --robot.id=<id>
# Default path when --robot.id was not set (id defaults to "none").
FOLLOWER_CALIB_JSON = str(
    pathlib.Path.home()
    / ".cache/huggingface/lerobot/calibration/robots/so_follower/my_follower.json"
)


# Path to the SO-101 URDF (updated version with camera mount links).
# Used by so101_fk.py for documentation/validation only — FK values are
# hardcoded from the URDF to avoid a runtime XML parse dependency.
URDF_PATH = "calibration/so101_updated.urdf"

# ── ChArUco board (all prints identical) ─────────────────────────────
SQUARES_X = 8
SQUARES_Y = 11
SQUARE_LENGTH = 0.03001  # metres
MARKER_LENGTH = 0.02201  # metres
ARUCO_DICT = cv2.aruco.DICT_5X5_100
MIN_CHARUCO_CORNERS = 6

# ── Intrinsic calibration ─────────────────────────────────────────────
CALIB_MIN_IMAGES = 20  # minimum valid captures for intrinsics

# ── Hand-eye calibration ──────────────────────────────────────────────
HANDEYE_MIN_POSES = 15  # minimum poses (recommend 15-20)

# ── Phase 1/2/3 capture ───────────────────────────────────────────────
PHASE1_N_FRAMES = 15

# ── Real-world measurement ────────────────────────────────────────────
BOARD_X_FROM_ROBOT = 0.135   # metres — tape measured, robot +X axis
BOARD_Y_FROM_ROBOT = 0.0     # metres — assumed on centreline
BOARD_Z_FROM_ROBOT = 0.0     # metres — assumed table surface = robot Z=0

# ── Results ───────────────────────────────────────────────────────────
RESULTS_BASE_DIR = "results"
